name: Build .NET 8.0

on:
  push:
  pull_request:
    branches: [ master ]
    paths:
    - '**.cs'
    - '**.csproj'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs:
  build-net8:
    name: build-net8-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false    
      matrix:
        os: [windows-latest]    
        include:
          - framework: 'net8.0-windows'
            dotnet-version: '8.0.x'
            configuration: 'Release'
            customtesttarget: net8.0
            
    env:
      OS: ${{ matrix.os }}
      DOTNET_VERSION: ${{ matrix.dotnet-version }}
      CONFIGURATION:  ${{ matrix.configuration }}
      
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Build OpcDaAeHdaClientSolution.sln
      run: dotnet build --force --framework ${{ matrix.framework }} --configuration ${{ matrix.configuration }} "OpcDaAeHdaClientSolution.sln"

    - name: Build OpcDaAeHdaWorkshopClients.sln
      run: dotnet build --force --framework ${{ matrix.framework }} --configuration ${{ matrix.configuration }} "OpcDaAeHdaWorkshopClients.sln"
